version: 2

project_name: rockide

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/rockide
    ldflags:
      - -s -X main.version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
